# Generated by Django 2.1 on 2018-08-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(db_index=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='ushou',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
    ]
